version: '3.8'

services:
  app:
    build: .
    restart: always
    ports:
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    environment:
      - NODE_ENV=production
      - DOMAIN=qrdrop.pro
    networks:
      - app_network

networks:
  app_network:
    driver: bridge 